#!/usr/bin/env python3
"""Generate the self-contained code shipped in the bodhan-ai/indic-ocr Hub repo.

Usage:
    python3 hub/build_hub_package.py <staging_dir>

The inference stack is vendored alongside the weights so the Hub repo can be used
without installing the bodhan-genai package. The quickstart only needs:

    pip install transformers torch pillow

The generated modules are copied from src/bodhan_genai/ocr/. This file is the source
of the packaging rules; the vendored files themselves are never hand-edited.

The source package is flattened into top-level iocr_*.py modules. Imports are rewritten
accordingly, which means the snapshot can be added directly to sys.path without
trust_remote_code or a separately installed bodhan_genai package.

The vLLM backend and inference CLI are intentionally excluded. The Hub quickstart uses
the transformers-based recognizer, so the vendored copy must not import vLLM.
"""

import re
import shutil
import sys
from pathlib import Path

SRC = Path(__file__).resolve().parents[1] / "src" / "bodhan_genai" / "ocr"
HUB = Path(__file__).resolve().parent

#: source module -> flat vendored name
MODULES = {
    "templates/contract.py": "iocr_contract.py",
    "engine/types.py": "iocr_types.py",
    "engine/blocks.py": "iocr_blocks.py",
    "engine/crops.py": "iocr_crops.py",
    "engine/reconstruct.py": "iocr_reconstruct.py",
    "engine/layout.py": "iocr_layout.py",
    "engine/recognizer.py": "iocr_recognizer.py",
    "engine/offline.py": "iocr_offline.py",
    "engine/checkpoints.py": "iocr_checkpoints.py",
    "layout/labels.py": "iocr_model_labels.py",
    "layout/order_loss.py": "iocr_model_order_loss.py",
    "layout/modeling_ppdoc.py": "iocr_model_ppdoc.py",
    "layout/infer.py": "iocr_model_infer.py",
}

#: dotted source path -> flat module, for rewriting imports
REWRITE = {
    "bodhan_genai.ocr.templates.contract": "iocr_contract",
    "bodhan_genai.ocr.engine.types": "iocr_types",
    "bodhan_genai.ocr.engine.blocks": "iocr_blocks",
    "bodhan_genai.ocr.engine.crops": "iocr_crops",
    "bodhan_genai.ocr.engine.reconstruct": "iocr_reconstruct",
    "bodhan_genai.ocr.engine.layout": "iocr_layout",
    "bodhan_genai.ocr.engine.recognizer": "iocr_recognizer",
    "bodhan_genai.ocr.engine.offline": "iocr_offline",
    "bodhan_genai.ocr.engine.checkpoints": "iocr_checkpoints",
    "bodhan_genai.ocr.layout.labels": "iocr_model_labels",
    "bodhan_genai.ocr.layout.order_loss": "iocr_model_order_loss",
    "bodhan_genai.ocr.layout.modeling_ppdoc": "iocr_model_ppdoc",
    "bodhan_genai.ocr.layout.infer": "iocr_model_infer",
}

BANNER = (
    "# GENERATED by hub/build_hub_package.py from src/bodhan_genai/ocr/{src} -- do not edit.\n"
    "# Vendored so this repo is self-contained: `pip install transformers torch pillow` is the\n"
    "# whole install. See indic_ocr.py for usage.\n"
)


#: In the vendored copy the only recognizer is the transformers one, so the default backend
#: changes with it. Left alone this would import recognizer_vllm and drag vLLM back in.
VLLM_DEFAULT = """        if backend is None:
            from bodhan_genai.ocr.engine.recognizer_vllm import VllmRecognizer

            backend = VllmRecognizer(ckpt, self.config)"""
HF_DEFAULT = """        if backend is None:
            from iocr_recognizer import HfRecognizer

            backend = HfRecognizer(ckpt, self.config)"""


def rewrite(text: str, src_name: str) -> str:
    text = text.replace(VLLM_DEFAULT, HF_DEFAULT)
    for dotted, flat in sorted(REWRITE.items(), key=lambda kv: -len(kv[0])):
        text = text.replace(f"from {dotted} import", f"from {flat} import")
        text = text.replace(f"import {dotted}", f"import {flat}")
    # The vendored layout modules were siblings inside a package, so they import each other
    # relatively; repoint those at the flat names. Derived from MODULES rather than by mangling
    # the name, because the two do not correspond (layout/modeling_ppdoc.py -> iocr_model_ppdoc).
    #
    # Leading whitespace is captured deliberately: layout/infer.py imports modeling_ppdoc from
    # INSIDE a function, so anchoring at column 0 skips it and the module is missing at load.
    siblings = {
        Path(src).stem: flat[:-3] for src, flat in MODULES.items() if src.startswith("layout/")
    }
    text = re.sub(
        rf"^(\s*)from \.({'|'.join(siblings)}) import",
        lambda m: f"{m.group(1)}from {siblings[m.group(2)]} import",
        text,
        flags=re.M,
    )
    return BANNER.format(src=src_name) + "\n" + text


def main() -> int:
    dest = Path(sys.argv[1]) if len(sys.argv) > 1 else HUB / "_staged"
    dest.mkdir(parents=True, exist_ok=True)

    for src_rel, flat in MODULES.items():
        source = SRC / src_rel
        if not source.exists():
            sys.exit(f"missing source module: {source}")
        (dest / flat).write_text(rewrite(source.read_text(encoding="utf-8"), src_rel), "utf-8")

    shutil.copy(HUB / "indic_ocr.py", dest / "indic_ocr.py")

    # The vendored copy must stand alone: no vLLM (the quickstart path has no vLLM installed)
    # and no bodhan_genai (nothing of ours is installed at all).
    scanner = re.compile(r"^\s*import\s+(\S+)\s*$|^\s*from\s+(\S+)\s+import", re.M)
    required = set()
    for path in dest.glob("*.py"):
        for a, b in scanner.findall(path.read_text(encoding="utf-8")):
            dotted = a or b
            if dotted and not dotted.startswith("."):
                required.add(dotted.split(".")[0])
    stdlib = {
        "__future__",
        "argparse",
        "base64",
        "dataclasses",
        "enum",
        "html",
        "importlib",
        "io",
        "json",
        "logging",
        "math",
        "os",
        "re",
        "subprocess",
        "sys",
        "tempfile",
        "typing",
        "pathlib",
        "collections",
        "warnings",
    }
    vendored = {flat[:-3] for flat in MODULES.values()} | {"indic_ocr"}
    third_party = sorted(required - stdlib - vendored)
    leaked = [m for m in third_party if m in ("vllm", "bodhan_genai")]
    if leaked:
        sys.exit(f"the vendored copy still requires {leaked}; it must be self-contained")

    # Every iocr_* import must resolve to a file actually emitted here. Without this, adding a
    # module to src/ that the vendored copy imports but MODULES does not list would ship a
    # release that fails at import with ModuleNotFoundError.
    dangling = sorted(m for m in required if m.startswith("iocr_") and m not in vendored)
    if dangling:
        sys.exit(f"vendored modules import {dangling}, which MODULES does not emit")

    print(f"  {len(MODULES) + 1} files -> {dest}")
    print(f"  requires only: {', '.join(third_party)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
